# Generated by Django 5.2.1 on 2025-05-12 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Afrikaans', 'af'), ('Albanian', 'sq'), ('Amharic', 'am'), ('Arabic', 'ar'), ('Armenian', 'hy'), ('Asturian', 'ast'), ('Azerbaijani', 'az'), ('Bengali', 'bn'), ('Bosnian', 'bs'), ('Breton', 'br'), ('Bulgarian', 'bg'), ('Burmese', 'my'), ('Catalan', 'ca'), ('Cebuano', 'ceb'), ('Chinese (Simplified)', 'zh'), ('Croatian', 'hr'), ('Czech', 'cs'), ('Danish', 'da'), ('Dutch', 'nl'), ('English', 'en'), ('Estonian', 'et'), ('Finnish', 'fi'), ('French', 'fr'), ('Galician', 'gl'), ('Georgian', 'ka'), ('German', 'de'), ('Greek', 'el'), ('Gujarati', 'gu'), ('Haitian Creole', 'ht'), ('Hausa', 'ha'), ('Hebrew', 'he'), ('Hindi', 'hi'), ('Hungarian', 'hu'), ('Icelandic', 'is'), ('Igbo', 'ig'), ('Indonesian', 'id'), ('Irish', 'ga'), ('Italian', 'it'), ('Japanese', 'ja'), ('Javanese', 'jv'), ('Kannada', 'kn'), ('Kazakh', 'kk'), ('Khmer', 'km'), ('Korean', 'ko'), ('Kurdish', 'ku'), ('Kyrgyz', 'ky'), ('Lao', 'lo'), ('Latin', 'la'), ('Latvian', 'lv'), ('Lithuanian', 'lt'), ('Luxembourgish', 'lb'), ('Malagasy', 'mg'), ('Malay', 'ms'), ('Malayalam', 'ml'), ('Maori', 'mi'), ('Marathi', 'mr'), ('Mongolian', 'mn'), ('Nepali', 'ne'), ('Norwegian', 'no'), ('Persian (Farsi)', 'fa'), ('Polish', 'pl'), ('Portuguese', 'pt'), ('Punjabi', 'pa'), ('Romanian', 'ro'), ('Russian', 'ru'), ('Sindhi', 'sd'), ('Sinhala', 'si'), ('Slovak', 'sk'), ('Slovenian', 'sl'), ('Somali', 'so'), ('Spanish', 'es'), ('Sundanese', 'su'), ('Swahili', 'sw'), ('Swedish', 'sv'), ('Tagalog (Filipino)', 'tl'), ('Tamil', 'ta'), ('Telugu', 'te'), ('Thai', 'th'), ('Turkish', 'tr'), ('Ukrainian', 'uk'), ('Urdu', 'ur'), ('Uzbek', 'uz'), ('Vietnamese', 'vi'), ('Welsh', 'cy'), ('Yoruba', 'yo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('is_doctor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Profile Images/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('language_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('transcription_error', models.BooleanField(default=False)),
                ('original_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_language', to='api.language')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_sessions', to=settings.AUTH_USER_MODEL)),
                ('translated_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_language', to='api.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='translation_audio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.translationsession')),
            ],
        ),
    ]
