
services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    networks:
      - app_network

  backend:
    build: 
      context: ./backend
    container_name: backend_service
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      sh -c "
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 healthcare_ai_translation.wsgi:application"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
  static_volume:
  media_volume:
