version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_service
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    command: >
      gunicorn --bind 0.0.0.0:8000 healthcare_ai_translation.wsgi:application
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:80" # Serve on localhost:3000
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
  static_volume:
  media_volume:
